### sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "boob@mail.com",
    "username": "boob",
    "password": "password"
}

### sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "username": "boob",
    "password": "password"
}

### update
PATCH http://localhost:3000/auth/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inlhb29vbyIsInN1YiI6MSwiaWF0IjoxNjM3MzYzNjk4LCJleHAiOjE2MzczNjcyOTh9.iOI7OMVssPrm0eYOhNpALY0-w96MMl5MwmsnQXRCwkY

{
    "username": "aazooo"
}

### get user by id
GET http://localhost:3000/users/1

### get user by name
GET http://localhost:3000/users?username=bob