### sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "bb@mail.com",
    "username": "bob",
    "password": "password"
}

### sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "username": "bob",
    "password": "password"
}

### update
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "username": "yayao"
}

### get user by id
GET http://localhost:3000/users/1

### get user by name
GET http://localhost:3000/users?username=bob