name: CI

on:
  push:
    paths-ignore:
      - ./**/README.md
      - ./frontend/**
      - ./**/.gitignore
  pull_request:
    paths-ignore:
      - ./**/README.md
      - ./frontend/**
      - ./**/.gitignore

jobs:
  backend-unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 17.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
      working-directory: ./backend
    - run: npm test
      working-directory: ./backend
    - run: npm run test:cov
      working-directory: ./backend


  # backend-e2e-test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 25
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       node-version: [14.x, 16.x, 17.x]
  
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}

  #   - run: yarn install
  #     working-directory: ./backend
  #   - run: yarn run test:e2e
  #     working-directory: ./backend

  # frontend-unit-test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 25
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       node-version: [12.x, 14.x, 16.x]
    
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}

  #   - run: sh -c 'npm install && npm run serve'
  #     working-directory: ./frontend
